### PR TITLE
fixed maxlength for challenge description text

### PR DESCRIPTION
**Pull request by FelixHultman**
maxlength
added a maxlength to the description on challenges. it looks like shit imo, but if they want it they get it.

### CODE REVIEW

**Review by JrSchoolAccount — APPROVED** [review]
Simple, yet elegant👍

**Review by NelsonTheBrave — COMMENTED** [review]
Haha, like your comment! idk, I guess we should just do what the beställare asks of us ;) Anyway, my only feedback is that you could make the code one line shorter by using this.data.description as the parameter in the if statement, and thus not having to repeat the same line of code twice (lines 83 and 89), if you see what I mean?

**Comment by FelixHultman** [comment]
> Haha, like your comment! idk, I guess we should just do what the beställare asks of us ;) Anyway, my only feedback is that you could make the code one line shorter by using this.data.description as the parameter in the if statement, and thus not having to repeat the same line of code twice (lines 83 and 89), if you see what I mean?

**Comment by FelixHultman** [comment]
> > Haha, like your comment! idk, I guess we should just do what the beställare asks of us ;) Anyway, my only feedback is that you could make the code one line shorter by using this.data.description as the parameter in the if statement, and thus not having to repeat the same line of code twice (lines 83 and 89), if you see what I mean?

good feedback, fixed now. i just removed the else statement since its not needed

**Pull request merged**
